# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSE2K0lt1DnOYHf2I9c99TlwhrhpuUwn
"""

print("hello")